### PR TITLE
Long string support

### PR DESCRIPTION
**Pull request by anjohnson**
This code was pretty easy to write, thanks! Tested and seems to be working.

I just noticed that my additions to `doc/readme.txt` don't mention that the support for long string records is for Base-3.15 only, although that does appear in the `changes.txt` entry.

I discovered when test-building against 3.14 that the new `configure/` files only actually work against Base versions back to R3.14.11, hence the note I added to your `changes.txt` item about them.

### CODE REVIEW

**Comment by kasemir** [comment]
> versions back to R3.14.11
We're using R3.14.11, or 3.14.12.6, so just making the cut!

**Comment by kasemir** [comment]
Thanks for the additions and hints regarding warning and MAX_STRING...

There is a remaining warning `‘rset’ is deprecated`. Is there an easy way to fix that, or would it require `ifdef .. EPICS Version..`?

**Comment by anjohnson** [comment]
I'll fix the rset deprecation next, don't make a release until you another PR from me for that.

**Comment by kasemir** [comment]
OK, thanks for looking into it.

**Pull request merged**
