### PR TITLE
Added stringout support

### PR DESCRIPTION
**Pull request by wmoore28**
Support was done by William Lu (JLAB) for ether_ip-2-23.  I added his changes to the 2-23 version.  Only adding stringout support, no other mods.  Then merged latest ether_ip changes on top of it without conflict.  Testing here showed correct behavior of 39-char strings (EPICS limit + \0).  Please evaluate for later merge into master.

### CODE REVIEW

**Comment by kasemir** [comment]
Thank you, looks good!
I appreciate how you based the older change on the current sources, so it's really a minimal change that only adds the stringout support.

Can you add another commit to update the version number (next would be 2-27 based on where we're now) and mention it in the changes.txt?

**Comment by wmoore28** [comment]
Sure no problem.  Just update changes.txt with date/version/comments and resubmit?

**Comment by kasemir** [comment]
version.txt, and in there you'll see that it mentions the #defines ETHERIP_MAYOR and ETHERIP_MINOR in ether_ipApp/src/drvEtherIP.h, to update them to match.

Thanks!

**Comment by wmoore28** [comment]
Updated the versions and added the comments for the 2-27 release.  Let me know if anything else is needed.  Thanks Kay!

**Comment by kasemir** [comment]
OK, pulled that in the master branch.
Thanks a lot!

**Pull request merged**
